"""Factory defaults kept outside the legacy runtime engine."""
from __future__ import annotations

from app.config import (
    DEFAULT_GRADIENT_COLOR2,
    DEFAULT_SOLID_COLOR,
    DEFAULT_THEME_COLOR,
    IS_WINDOWS,
)


def build_default_config() -> dict:
    """Return a fresh factory-default configuration dictionary."""
    return {
        "mode": "幻灯片放映",
        "slide_folder": "",
        "slide_seconds": 300,
        "transition_effect": "system",
        "transition_direction": "right",
        "transition_duration_ms": 300,
        "wallpaper_transition_enabled": True,
        "wallpaper_transition_policy_version": 1,
        "video_file": "",
        "video_muted": True,
        "video_volume": 100,
        "video_focus_behavior": "none",
        "video_focus_duck_volume": 20,
        "html_file": "",
        "html_auto_pause": True,
        "html_frame_rate": 30,
        "shuffle": False,
        "fit_mode": "填充",
        "single_image": "",
        "solid_color": DEFAULT_SOLID_COLOR,
        "gradient_color2": DEFAULT_GRADIENT_COLOR2,
        "theme_color": DEFAULT_THEME_COLOR,
        "gradient_angle": 60,
        "current_wallpaper": "",
        "slideshow_last_wallpaper": "",
        "history": [],
        "favorites": [],
        "auto_start": False,
        "auto_start_prompt_shown": False,
        "ctx_last_wallpaper": False,
        "ctx_next_wallpaper": False,
        "ctx_random_wallpaper": False,
        "ctx_jump_to_wallpaper": False,
        "hotkey_previous": "Ctrl+Alt+U",
        "hotkey_next": "Ctrl+Alt+N",
        "hotkey_random": "Ctrl+Alt+R",
        "hotkey_jump": "Ctrl+Alt+J",
        "hotkey_focus_guard": bool(IS_WINDOWS),
        "global_hotkeys_enabled": False,
        "app_shortcuts_enabled": True,
        "app_shortcuts": {
            "previous": "PgUp",
            "next": "PgDown",
            "random": "R",
            "bing": "F5",
            "settings": "Ctrl+,",
            "exit": "Ctrl+Q",
            "hide_to_tray": "Esc",
        },
        "recent_folders": [],
        "run_in_background": True,
        "tray_icon": True,
        "tray_notify": True,
        "tray_click_action": "next",
        "tray_menu_items": ["show", "previous", "next", "random", "bing", "jump", "about", "exit"],
        "dark_mode": False,
        "enable_animations": True,
        "performance_mode": False,
        "performance_level": "balanced",
        "silent_update_check_on_startup": True,
        "bing_cache_dir": "",
        "bing_sync_count": 1,
        "bing_next_index": 0,
        "bing_auto_cleanup": False,
        "bing_auto_update_on_start": False,
        "bing_auto_update_count": 1,
        "bing_auto_delete_on_start": False,
        "bing_auto_delete_count": 1,
        "log_enabled": False,
        "log_file_path": "",
        "ignored_version": "",
        "ignored_dependency_warning_signature": "",
        "app_theme": "default",
        "font_path": "",
        "font_weight": "normal",
        "font_size": 0,
        "dpi_scale": 1.0,
        "language": "zh",
    }
